services:
  # Backend API Java
  java-app:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: java-api-exam
    ports:
      - "8008:8008"
    restart: unless-stopped
    networks:
      - app-network

  # Frontend React
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: java-api-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - java-app

networks:
  app-network:
    driver: bridge